import Head from "next/head";
import { Box, Heading } from "@chakra-ui/react";
import Trainers from "@/data/trainers";
import Trainer from "@/components/trainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokémon Teams</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" w={{ base: "100%", lg: "80%" }}>
        <Heading as="h1" mb={12}>
          Pokémon Teams
        </Heading>

        {Trainers.map((trainer) => (
          <Trainer
            key={trainer.name}
            name={trainer.name}
            battles={trainer.battles}
          />
        ))}
      </Box>
    </>
  );
}
